version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: cpms-backend
    ports:
      - "5001:5000"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - cpms_network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cpms-frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    networks:
      - cpms_network
    restart: unless-stopped
    depends_on:
      - backend

networks:
  cpms_network:
    driver: bridge
